version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t auth-service .
      - docker tag auth-service 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/myregistry:auth-service
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/myregistry:auth-service
      - echo Writing definition files
      - printf '[{"name":"auth-service-container","imageUri":"%s"}]' 274201610284.dkr.ecr.$AWS_REGION.amazonaws.com/myregistry:auth-service > imagedefinitions.json

artifacts:
  files: imagedefinitions.json